# Generated by Django 3.0.7 on 2020-06-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Intrebare', 'verbose_name_plural': 'Intrebari'},
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='Text la intrebare', max_length=250),
        ),
    ]
