version: '3.7'
services:
    db:
        image: postgres:12.2
        env_file: .env
    console:
        build: .
        volumes:
            - .:/polls
        ports:
            - 8000:8000
        env_file: .env
        command: django-admin runserver 0.0.0.0:8000
        links:
            - db
        depends_on:
            - db
    frontend:
        build: frontend
        command: npm start
        ports:
            - 3000:3000
        depends_on:
            - console
