version: '3.7'
services:
    cache:
        image: memcached
    db:
        image: postgres:12.2
        env_file: .env
    console:
        build: .
        volumes:
            - .:/polls
        ports:
            - 8000:8000
        env_file: .env
        command: django-admin runserver 0.0.0.0:8000
        links:
            - db
            - cache
        depends_on:
            - db
            - cache
