# Generated by Django 3.0.5 on 2020-05-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200518_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bani',
            field=models.IntegerField(null=True),
        ),
    ]
