# Generated by Django 3.0.5 on 2020-05-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200520_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reprezentant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('prenume', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.IntegerField()),
                ('functie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('adresa', models.CharField(max_length=255)),
                ('cui', models.IntegerField()),
                ('reprezentant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Reprezentant')),
            ],
        ),
    ]
